### PR TITLE
Fix route host with placeholder

### PR DESCRIPTION
**Pull request by piotrantosik**
I have a routing file:
```yml
api_v1:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /v1
    host:     api.{domain}
    defaults:
        domain: "%domain%"
    requirements:
        domain: "%domain%"
```

Currently documentation looks like this:
route

After this PR placeholder is replacement by default parameter:

route2

### CODE REVIEW

**Comment by willdurand** [comment]
Does not work well on all supported Symfony versions

**Comment by piotrantosik** [comment]
Just noticed, I'll try to fix it asap

**Comment by piotrantosik** [comment]
@willdurand fixed, also remove duplicated assertions

**Comment by willdurand** [comment]
Perfect! Thank you.

**Pull request merged**
