### PR TITLE
Added basic array handling to address issue #564

### PR DESCRIPTION
**Pull request by advancingu**

### CODE REVIEW

**Comment by willdurand** [comment]
Could you please cover this patch with a test case?

**Comment by feridmovsumov** [comment]
@advancingu will you provide test cases for this pull request? We really need this change.

**Comment by advancingu** [comment]
@feridmovsumov Sorry, I'm too busy at the moment. Eventually might get around to it but not any time soon.

**Comment by feridmovsumov** [comment]
@advancingu I can help you. I will try to add test cases and I will send pull request to your repo. https://github.com/nelmio/NelmioApiDocBundle

**Comment by advancingu** [comment]
:+1:

**Comment by willdurand** [comment]
no test = no merge, sorry :)

**Pull request closed without merging**
