### PR TITLE
Added Doctrine support, get some troubble with ObjectModelDescriber.p…

### PR DESCRIPTION
**Pull request by betzholz**
…hp so deactived him.
also i added the possibility to update a schema by a second model disscriber.

### CODE REVIEW

**Comment by GuilhemN** [comment]
If the issue is that you have models named `int`, etc. this could be solved easily by inlining built-in types in `ObjectModelDescriber`.

**Comment by BigZ** [comment]
Let us know more about the problems your facing @betzholz

**Comment by betzholz** [comment]
Hey sorry for the late response.
I got for all primitives somthing like:  "string: { type: "string"}, int: {type: "integer"}", so the definition is valid but not nice...
If you dont use the ObjectModelDescriber everything in my cases is fine... but i bet this is not an option ;)
I think this s a result of overwriting... in my version the modelregestry allowes the decriber to overwrite the other descripter or rather complement the schema, so that many sources can bee used.

**Comment by GuilhemN** [comment]
Should be fixed by https://github.com/nelmio/NelmioApiDocBundle/pull/1125 :)

**Pull request closed without merging**
