### PR TITLE
defaultRouteDisabled to handle attributes

### LINKED ISSUE #2009: Using disable_default_routes filters out routes using attributes
Given this config
```yaml
nelmio_api_doc:
  areas:
    disable_default_routes: true
```
And this controller
```php
<?php

namespace App\Action;

use OpenApi\Attributes as OA;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;

class TestAction
{
    #[Route('/api/test', methods: ['POST'])]
    #[OA\Post(
        operationId: 'test',
        summary: 'Test endpoint',
        tags: ['Test'],
        responses: [
            new OA\Response(response: 201, description: 'test'),
            new OA\Response(response: 400, description: 'Bad request')
        ],
    )]
    public function __invoke() : JsonResponse
    {
        return new JsonResponse(['success']);
    }
}
```

No docs are generated.
image

### PR DESCRIPTION
**Pull request by JohnstonCode**
fixes #2009

### CODE REVIEW

**Comment by GuilhemN** [comment]
Thank you @JohnstonCode for opening a pull request!
Rather than instanciating all attributes, I'd feel more safe using the instanceof flag of getAttributes, to avoid loading broken attributes from other libraries (see https://www.php.net/manual/fr/reflectionclass.getattributes.php).

Would you be able to do the change?

**Comment by JohnstonCode** [comment]
Yes ill make that change ASAP

**Comment by bobvandevijver** [comment]
I've just hit this issue as well, is there any progress on this @JohnstonCode?

**Comment by JohnstonCode** [comment]
@GuilhemN I have made the requested changes

**Pull request merged**
