### PR TITLE
Fix map support of FOSRestBundle

### PR DESCRIPTION
**Pull request by GuilhemN**
Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1465

### CODE REVIEW

**Comment by spolischook** [comment]
If almost works
Selection_063
it generates parameters as `id=1465,145` but should `id[]=1465&id[]=145`

**Comment by GuilhemN** [comment]
This is most likely a bug in swagger-ui (see https://github.com/nelmio/NelmioApiDocBundle/issues/1490). I'm not sure what to do about this one, maybe it is fixed in the latest versions of swagger-ui and we only need to bump it

**Comment by spolischook** [comment]
why this closed?

**Comment by GuilhemN** [comment]
The correct fix was https://github.com/nelmio/NelmioApiDocBundle/pull/1509, right?

**Comment by spolischook** [comment]
it was changes to your changes in this PR - so this PR was updated and should be merged as well

**Comment by spolischook** [comment]
I have choose your branch as target for my PR

**Comment by GuilhemN** [comment]
Oops, you're right I didn't realize your PR wasn't targetting master :)
Thanks for the reminder!

**Pull request merged**
