### PR TITLE
Do not override SimpleFormatter::format to use processCollection

### LINKED ISSUE #667: Missing relations on simple formatter
With the following serializer entity configuration:

``` yaml
AppBundle\Entity\Server:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [list, details]
        name:
            expose: true
            groups: [list, details]
        status:
            expose: true
            groups: [list, details]
        hostedDomain:
            expose: true
            groups: [list, details]
        alias:
            expose: true
            groups: [details]
        owners:
            expose: true
            groups: [details]
        sshUser:
            expose: true
            groups: [list_admin, details_admin]
        sshPort:
            expose: true
            groups: [list_admin, details_admin]
        mysqlServer:
            expose: true
            groups: [details_admin]
        addedAt:
            expose: true
            groups: [details_admin]
```

And the following controller action:

``` php
/**
 * @ApiDoc(
 *  description="Returns server information",
 *  output={
 *      "class"="AppBundle\Entity\Server",
 *      "groups"={"details"},
 *      "parsers"={
 *          "Nelmio\ApiDocBundle\Parser\JmsMetadataParser"
 *      }
 *  }
 * )
 *
 * @param Server $server
 *
 * @return Response
 */
public function getAction(Server $server)
{
    $view = $this->view($server, 200);
    $context = new SerializationContext();
    $context->setGroups(['details']);
    $view->setSerializationContext($context);

    return $this->handleView($view);
}
```

I got the following **right** rendering on nelmio template:

nelmio_template

But if I try to get it from simple content in order to render a custom view:

``` php
$extractedDoc = $this->get('nelmio_api_doc.extractor.api_doc_extractor')->all();
$simpleContent = $this->get('nelmio_api_doc.formatter.simple_formatter')->format($extractedDoc);
dump($simpleContent);
```

I got this:

```
array:2 [▼
  "/api/servers" => array:2 [▼
    0 => array:9 [▶]
    1 => array:9 [▼
      "method" => "GET"
      "uri" => "/api/servers/{server}.{_format}"
      "description" => "Returns server information"
      "requirements" => array:2 [▶]
      "response" => array:6 [▼
        "id" => array:9 [▶]
        "name" => array:9 [▶]
        "alias" => array:9 [▶]
        "hosted_domain" => array:9 [▶]
        "status" => array:9 [▶]
        "owners" => array:10 [▶]
      ]
      "https" => false
      "authentication" => false
      "authenticationRoles" => []
      "deprecated" => false
    ]
  ]
  "/api/user" => array:1 [▶]
]
```

As you can see, relations are not here.

Is this an issue or am I missing something?

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Fixes #667.

In a nutshell, format methods are not overriden anymore to take profit of `processCollection` method.

Rendering method just returns the data output.

Not sur if it's the good way but works and solve my issue.

Feel free for remarks and suggestions.

### CODE REVIEW

**Comment by willdurand** [comment]
Sounds good to me tbh, see my comment in #667

**Comment by Soullivaneuh** [comment]
Also not sure for this: https://github.com/nelmio/NelmioApiDocBundle/pull/668/files#diff-db248d9b058e91724b6d96870fd387eeR29

But the parent array only contains `_others` for my case, what does it mean?

**Comment by Soullivaneuh** [comment]
Another thing, the actual rendering is not the best IMHO:

```
array:11 [▼
  "id" => array:10 [▶]
  "name" => array:10 [▶]
  "alias" => array:10 [▶]
  "hosted_domain" => array:10 [▶]
  "status" => array:10 [▶]
  "owners[]" => array:10 [▶]
  "owners[][username]" => array:10 [▶]
  "owners[][email]" => array:10 [▶]
  "owners[][firstname]" => array:10 [▶]
  "owners[][lastname]" => array:10 [▶]
  "owners[][locale]" => array:10 [▶]
]
```

Insead of `owners[][locale]`, why not using sub arrays? Any idea about a enhancement for this?

**Comment by willdurand** [comment]
That one is closed, like all other PRs. Please read why: https://github.com/nelmio/NelmioApiDocBundle/releases/tag/2.10.0.

**Comment by Soullivaneuh** [comment]
Ok I see. Could you please re-open it? I'll make a rebase.

**Comment by willdurand** [comment]
ping @Soullivaneuh

**Comment by Soullivaneuh** [comment]
@willdurand done.

**Comment by willdurand** [comment]
Looks like it broke several tests.

**Comment by Soullivaneuh** [comment]
Sigh, was not. :-(

I'll take a look later.

**Comment by Soullivaneuh** [comment]
@willdurand Should be OK now. :+1:

**Comment by Soullivaneuh** [comment]
@willdurand I don't understand the failures, I can't reproduce it on local...

**Comment by Soullivaneuh** [comment]
ping @willdurand. Any idea?

**Comment by willdurand** [comment]
I'll give it a try. I'd like to ship `2.11.0` by the end of this week.

**Comment by willdurand** [comment]
changed the milestone to get symfony 3.0 support first.

**Comment by Soullivaneuh** [comment]
Hey @willdurand! What should we do for this PR now? :-)

**Comment by Soullivaneuh** [comment]
@GuilhemN Well, maybe could you please give some details of why you closed this PR?

Thanks.

**Comment by GuilhemN** [comment]
Github closed it automatically because I changed the master branch.
Feel free to reopen it of course ;)

**Pull request closed without merging**
