### PR TITLE
Filter validations by groups

### PR DESCRIPTION
**Pull request by ghanbari**
User can specify groups for validations when input class is a form type.

### CODE REVIEW

**Comment by willdurand** [comment]
I cannot accept new features for now, sorry :(

**Comment by aistis-** [comment]
Also interested in this feature.

**Comment by idchlife** [comment]
@willdurand why not? Just interested

**Comment by willdurand** [comment]
I cannot accept new features because I am the only maintainer for too long, and I am not able to dedicate a lot of time to this bundle... Hence, I chose to feature-freeze this project.

**Comment by idchlife** [comment]
@willdurand thanks for the answer! Your bundle is really, really good in case of working with Symfony with api documentation. If I'm not mistaken, best so far, if not actually only one so far for swagger api doc.

**Comment by aistis-** [comment]
@willdurand Please keep this PR open :disappointed:

**Pull request closed without merging**
