### PR TITLE
#437 hide form type documentation

### PR DESCRIPTION
**Pull request by dpcat237**
Related to https://github.com/nelmio/NelmioApiDocBundle/issues/437. I added an optional config parameter to hide FormType documentation and documentation for the new parameter.

### CODE REVIEW

**Comment by willdurand** [comment]
Closing as I am not able to accept new features right now.

**Comment by dpcat237** [comment]
@willdurand when you will be accepting new features?

**Comment by willdurand** [comment]
Technically, it adds a new configuration option (that is why I believe it is more an improvement than a bug fix). I don't know when I'll be accepting new features again. Also, see: https://twitter.com/couac/status/742266704575758336.

**Comment by dbu** [comment]
the bundle now has new maintainers - if you are still interested @dpcat237 , please do a pull request against version 3 (master) of the bundle.

**Pull request closed without merging**
