### PR TITLE
[Feature] collapsible sections in json-response

### PR DESCRIPTION
**Pull request by leberknecht**
Aloha!
I would like to have the ability to collapse certain sections of the json-response.

And i adjusted the ValidationParserTest, otherwise i got an error that `validator.mapping.class_metadata_factory` is not defined because it was removed after compiling the container due to RemovePrivateAliasesPass (running on sf2 v2.6.5)

### CODE REVIEW

**Comment by filipegarcia** [comment]
:+1:

**Comment by lotas** [comment]
+1

**Comment by arosslau** [comment]
+1

**Comment by willdurand** [comment]
thanks!`

**Pull request merged**
