### PR TITLE
revert fix "LINK workaround for firefox"

### LINKED ISSUE #621: Sandbox - LINK is sent via POST with _method parameter (UNLINK is not)
Sending a LINK request is done via [method faking](http://symfony.com/doc/current/cookbook/routing/method_parameters.html#faking-the-method-with-method), so it sends a POST.
I believe it is a bug, since UNLINK and other methods are used directly.
Also, since LINKing is used on a non-collection resource like /something/1, the POST method would be disabled on it and a '405 Method Not Allowed' error is thrown.

If it is because of the [firefox bug](http://stackoverflow.com/questions/9649972/firefox-overwrites-custom-http-method-link-to-mixed-case-link-on-xhr), that one seems to be [fixed](https://bugzilla.mozilla.org/show_bug.cgi?id=477578) already.

### PR DESCRIPTION
**Pull request by tonivdv**
Reverts a previous fix for Firefox which is causing issues with Chrome and which is not necessary anymore for Firefox because they fixed the issue (https://bugzilla.mozilla.org/show_bug.cgi?id=477578)

Also Fixes #621

### CODE REVIEW

**Comment by tonivdv** [comment]
Hm, not sure though why tests are failing ... any way to relaunch tests without committing something? /cc @willdurand

**Comment by tonivdv** [comment]
@willdurand I don't get why those tests fail for a change in the twig file? If you can help me out and can fix it!?

**Comment by willdurand** [comment]
@tonivdv I tracked the error. It appears since v2.7 as things related to `ChoiceList` have changed (cf. https://github.com/symfony/symfony/commit/03efce1b568379eac21d880e427090e43035f505)

**Comment by willdurand** [comment]
Well, actually there are different issues... Fixing (more or less) them one by one.

**Comment by tonivdv** [comment]
:+1:

**Pull request merged**
