### PR TITLE
Multiple api documentations

### PR DESCRIPTION
**Pull request by Nyholm**
This is a rebase of the work done by @jaytaph in #548. (This will fix issue #404)

I need some help and guidance to tell me if this PR breaks any more tests... When I run the tests for master on my machine I get 6 failures and 9 errors.

### CODE REVIEW

**Comment by willdurand** [comment]
Hi! This has been merged! Thank you!!!

**Comment by jtherin** [comment]
Thank you very much :D

**Comment by Nyholm** [comment]
Thank you for merging

**Comment by jaytaph** [comment]
Awesome! @Nyholm thanks for doing the rebase.

**Comment by willdurand** [comment]
I am rewriting the code, should land tomorrow or so.

**Comment by willdurand** [comment]
Ok done. I changed the name of the feature as `views` is more expressive than `api` IMO.

**Comment by Nyholm** [comment]
:+1:
Great work! I'm really looking forward to start using this now.

**Comment by willdurand** [comment]
@Nyholm I think the bundle is back to a "stable" state now. If you can try the `master` branch, it would be nice :)

**Comment by Nyholm** [comment]
Okey great. I will start testing with the master branch and see how it works out =)

**Pull request closed without merging**
