### PR TITLE
Added xhrFields: { withCredentials: true } to ajaxOptions

### PR DESCRIPTION
**Pull request by richaas**
Added xhrFields: { withCredentials: true } to ajaxOptions to enable
browser authentication for cross origin API requests.

### CODE REVIEW

**Comment by OskarStark** [comment]
look ok to me, can you please squash your commits?

**Comment by richaas** [comment]
Ok, commits squashed.

**Comment by OskarStark** [comment]
thank you

@richaas , looks like travis failed, can you please check that?

@willdurand travis is up to date and the tests should pass, right?

**Comment by willdurand** [comment]
Well it looks like something is wrong with Symfony 2.7, but it is not related to this PR.

**Pull request merged**
