### PR TITLE
Configurable views

### PR DESCRIPTION
**Pull request by goetas**
This PR adds configurable views: 
Each view can be configured.
```yaml
# app/config/config.yml
nelmio_api_doc:
    views:
      premium:
        include: ["code", "platinum", "secret"]
        include_empty: true
      simple:
        include: ["core", "secret"]
        include_empty: false
```    

* `include` will include into the `premium` view all the endpoints that belongs to "code", "platinum", "secret" views.
* `include_empty` will include into the `premium` all the endpoints has no specified views

### CODE REVIEW

**Comment by goetas** [comment]
something changed on the repo, now even master is failing https://travis-ci.org/goetas/NelmioApiDocBundle/builds/94669887

**Comment by goetas** [comment]
added some tests

**Comment by goetas** [comment]
rebased  to keep it in sync with the latest master

**Comment by willdurand** [comment]
Closing as I am not able to accept new features right now.

**Pull request closed without merging**
