### PR TITLE
Made ValidationParser respect validation groups

### PR DESCRIPTION
**Pull request by adsc**
Validation constraints are only evaluated if one of their groups is contained in the ApiDoc's "groups" array contained in the "input" specification.

### CODE REVIEW

**Comment by adsc** [comment]
I have fixed the problems, but the pull request is not updating for some reason. Should I close this one and make a new one?

**Comment by barmarko27** [comment]
Hi, there are news?
I've the same problem with validation groups (ignored).
Thanks so much! 👍

**Comment by JustBlackBird** [comment]
Is there any progress on this PR?

**Comment by jekamell** [comment]
Any news about this? I have the same problem :(

**Pull request closed without merging**
