### PR TITLE
Fix NelmioApiDocBundle view customization instructions

### PR DESCRIPTION
**Pull request by chteuchteu**
"Just create a file..." was not OK (missing views/ subdirectory, wrong SwaggerUi case)
The path showcased as code-block's first row was OK

### CODE REVIEW

**Comment by GuilhemN** [comment]
You're right about the case but `views` is not needed, see https://symfony.com/doc/master/bundles/override.html#templates.

**Comment by chteuchteu** [comment]
Alright! Should we completely strip it on both occurrences then?

**Comment by GuilhemN** [comment]
Yes indeed, `views` should be here at all :+1:

**Comment by chteuchteu** [comment]
@GuilhemN Done!

**Comment by GuilhemN** [comment]
Thanks @chteuchteu! :)

**Pull request merged**
