### PR TITLE
Support CSRF protection token of Symfony's form component

### PR DESCRIPTION
**Pull request by stollr**
This PR adds support of the CSRF protection token which is created by the Symfony form component if the `csrf_protection` option is enabled.

As soon as this option is enabled a corresponding property will be added to the schema. 

This PR addresses #2120.

There already was another PR (#411) some years ago, but it wasn't merged. I'd be happy if this could be accepted.

### CODE REVIEW

**Comment by stollr** [comment]
@GuilhemN I'd be really happy if you could have a look at this addition.

**Comment by DjordyKoert** [comment]
I would also like to see a functional test for this https://github.com/nelmio/NelmioApiDocBundle/tree/master/Tests/Functional/Form  😄

**Comment by DjordyKoert** [comment]
Thank you, could you please also write a test which shows the behaviour when using `configureOptions()` https://symfony.com/doc/current/security/csrf.html#csrf-protection-in-symfony-forms 😄

**Comment by stollr** [comment]
@DjordyKoert I have added some edge case handling and more tests. What do you think now?

**Comment by DjordyKoert** [comment]
Thank you @stollr!

**Pull request merged**
