### PR TITLE
Add more information to swagger doc

### PR DESCRIPTION
**Pull request by mjanser**
I added some more information to the output of the `SwaggerFormatter` like descriptions, min/max values and data types.

### CODE REVIEW

**Comment by mjanser** [comment]
I rebased this merge request and added some other minor enhancements. What do you think?

**Comment by mjanser** [comment]
ping @willdurand?

**Comment by willdurand** [comment]
A few tests would be nice

**Comment by mjanser** [comment]
Good idea, I added some tests.

**Comment by mjanser** [comment]
ping @willdurand?

**Pull request closed without merging**
