### PR TITLE
Add Api doc configuration in yaml file

### PR DESCRIPTION
**Pull request by oktapodia**
You can allow yaml or annotation format for api doc configuration

### CODE REVIEW

**Comment by oktapodia** [comment]
#435

**Comment by ajouve** [comment]
:+1:

**Comment by robholmes** [comment]
:+1: This is a great idea, as my annotations are getting huge!

**Comment by Khaldoun488** [comment]
:+1:

**Comment by Gta-Cool** [comment]
:+1:

**Comment by arnaudbaali** [comment]
:+1:

**Comment by lorianagnes** [comment]
:+1:

**Comment by oktapodia** [comment]
Can you read my PR please ? @willdurand

**Comment by SoboLAN** [comment]
A detailed is probably needed, but love the idea :+1:

**Comment by VEBERArnaud** [comment]
Hi
Do you plan to merge the PR #592 or add this feature soon ?

**Comment by oktapodia** [comment]
I don't know, I'm in waiting ^^ I resolve all the conflict tomorrow.

**Comment by SherifMedhat** [comment]
great feature, any updates?

**Comment by oktapodia** [comment]
I just updated this feature today, I added an autoloader, each bundles are parsed to find a yaml files in **Resources/nelmio** directory

The test are broken on master. It will be fixed in an other pull request...

**Comment by gastounage** [comment]
:+1:

**Comment by oktapodia** [comment]
ping @willdurand Can I have an update please ? Why my PR was closed ?

**Comment by willdurand** [comment]
Yup. Please read this: https://github.com/nelmio/NelmioApiDocBundle/releases/tag/2.10.0

**Pull request closed without merging**
