### PR TITLE
Add support for allowNull for Assert\NotBlank

### LINKED ISSUE #1647: @NotBlank and allowNull=true
Symfony's `@NotBlank` constraint allows to specify whether or not `null` values are allowed (`@NotBlank(allowNull=true)`). See [Symfony docs](https://symfony.com/doc/current/reference/constraints/NotBlank.html#allownull).

Currently, the bundle displays all properties with this annotation as required, even with `allowNull` set to `true`. 

My proposal: In case of `allowNull=true`, the property should not be marked as required.

What do you think?

### PR DESCRIPTION
**Pull request by akalineskou**
Fixes #1647

### CODE REVIEW

**Comment by akalineskou** [comment]
Can this fix be ported to the 3.x branch?
This is the version I'm currently using in my project.

**Comment by akalineskou** [comment]
For some weird reason the tests are failing https://travis-ci.org/github/nelmio/NelmioApiDocBundle/jobs/722862926

It expects the title to not be there in `Tests/Functional/JMSFunctionalTest.php`
```
                'virtual_type1' => [
                    'title' => 'JMS custom types handled via Custom Type Handlers.',
                    '$ref' => '#/components/schemas/VirtualTypeClassDoesNotExistsHandlerDefined',
                ],
                'virtual_type2' => [
                    'title' => 'JMS custom types handled via Custom Type Handlers.',
                    '$ref' => '#/components/schemas/VirtualTypeClassDoesNotExistsHandlerNotDefined',
                ],
```

This was supposed to be fetched from `Tests/Functional/Entity/JMSUser.php`
```
    /**
     * JMS custom types handled via Custom Type Handlers.
     *
     * @var string
     * @Serializer\Type("VirtualTypeClassDoesNotExistsHandlerDefined")
     * @Serializer\Expose
     */
    private $virtualType1;
```

Does any one have any idea if it's safe to delete from the test?
Or any other ideas to fix this error?

**Comment by GuilhemN** [comment]
Thank you @akalineskou! No need to fix the tests in this PR, the failure is not related to your changes ;)

I'll merge your changes in 3.x as soon as possible :)

**Comment by GuilhemN** [comment]
Merged in https://github.com/nelmio/NelmioApiDocBundle/commit/0da1909cb9aa42174dccdb06edc2a9bb17fb92da, thank you!

**Comment by akalineskou** [comment]
Do you have a possible timeline when this will be released to the 3.x version?

**Comment by GuilhemN** [comment]
I'll release it during the week end :)

**Comment by GuilhemN** [comment]
Done, see https://github.com/nelmio/NelmioApiDocBundle/releases/tag/v3.7.1

**Comment by akalineskou** [comment]
@GuilhemN tried it today, but it doesn't work anymore, I guess because `method_exists` will always return false since it's a property

**Pull request closed without merging**
