### PR TITLE
Create an enum model describer

### PR DESCRIPTION
**Pull request by magnetik**
I have not written any test, but it works fine for my usage : a simple enum used as a choice list in a property of an object.

ref #1963

### CODE REVIEW

**Comment by GuilhemN** [comment]
Thanks for working on this!

It seems there exists an integration in the symfony serializer (https://github.com/symfony/symfony/pull/40830) but only for backed enumarations.
So I am not sure we should try to document other enumerations as we would differ from the Symfony serializer behavior which we tried to mimic as much as possible until now.

What do you think? How are you dealing with normal enums serialization in your apps?

**Comment by magnetik** [comment]
Hi!

It was super early in our use of enums in the codebase, and we switched to only backed enums. 

I'll update the PR to support only them for now.

**Comment by GuilhemN** [comment]
I did not look into all the details but I believe the failure was due to an old bug in Api-Platform which has been fixed since.
Bumping Api-Platform's version seems to fix the tests so I guess we're good :)

**Comment by filkaris** [comment]
Hello! Thank you for your contribution since this is an issue we faced as well

@GuilhemN is there a planned release in the near future that would include this feature?

Thank you!

**Comment by GuilhemN** [comment]
@filkaris Sure! I just released 4.9.0: https://github.com/nelmio/NelmioApiDocBundle/releases/tag/v4.9.0.

**Pull request merged**
