### PR TITLE
Add support for redocly

### PR DESCRIPTION
**Pull request by Gabb1995**
Not sure what tests I can write for this, any help would be nice.

### CODE REVIEW

**Comment by Gabb1995** [comment]
PR for #1644

**Comment by asuri0n** [comment]
would love to see this feature come out

**Comment by misterxan** [comment]
@GuilhemN any updates about this PR?

**Comment by roykoper** [comment]
I'd like to see this come out, looks good!

**Comment by misterxan** [comment]
@DjordyKoert may be you can help us?

**Comment by DjordyKoert** [comment]
Thank you @Gabb1995 and my excuses for the long wait 😅

**Pull request merged**
