### PR TITLE
Change Namespace for DunglasApiProvider

### PR DESCRIPTION
**Pull request by jewome62**
The path of ClassMetadataFactory change on master of dunglas/DunglasApiBundle since July 29th

https://github.com/dunglas/DunglasApiBundle/commit/ed3635a1aa5f4f5848e25abf0b4230eadc37707b#diff-6af8d41bb3800a50340d17839a3481d3

### CODE REVIEW

**Comment by jewome62** [comment]
Composer.json
```json
"dunglas/api-bundle": "dev-master",
"nelmio/api-doc-bundle": "~2.9",
```

Error in all page with minimal configuration
```
ContextErrorException in DunglasApiProvider.php line 47: Catchable Fatal Error: Argument 3 passed to Nelmio\ApiDocBundle\Extractor\AnnotationsProvider\DunglasApiProvider::__construct() must be an instance of Dunglas\ApiBundle\Mapping\ClassMetadataFactoryInterface, instance of Dunglas\ApiBundle\Mapping\Factory\ClassMetadataFactory given, called in /var/www/project/var/cache/dev/appDevDebugProjectContainer.php on line 2491 and defined
```

**Comment by jewome62** [comment]
ping @dunglas

**Comment by dunglas** [comment]
The `dev-master` of DunglasApiBundle will be the 2.0 branch of API Platform and will introduce a lot of changes including a ton of BC break: new namespace, split between a standalone library and the bundle, new controller system (ADR pattern), new metadata system as you pointed out...

I think that there is no interest for now to support the `dev-master` branch as it's a big WIP and a lot of BC breaks will come.

I've just created a [`1.0` branch](https://github.com/dunglas/DunglasApiBundle/tree/1.0) that works fine with the current version of NelmioApiDocBundle. They will not be any BC break in that branch and I'll mark the first stable tag tomorrow.

For details see dunglas/DunglasApiBundle#253 and #685.

**Comment by dupuchba** [comment]
:+1: That's great ! I am very excited to try the standalone and hopefully help you.

**Comment by dunglas** [comment]
@dupuchba I've already pushed some code in a temporary branch but it's far from being usable: https://github.com/dunglas/DunglasApiBundle/tree/v2-metadata

**Comment by dupuchba** [comment]
ok, I just looked, but it would be great to explain your strategy. Final goal is to have a single dependency on the serializer right ?

**Pull request closed without merging**
