### PR TITLE
Added example configuration for request and response body

### PR DESCRIPTION
**Pull request by yoshz**
Rebased  #470 on master.
Please merge it this time :)

### CODE REVIEW

**Comment by willdurand** [comment]
I am not sure about it..

**Comment by yoshz** [comment]
About this feature or about the code?

**Comment by willdurand** [comment]
about the feature itself to be honest.

also, the `master` branch has changed a lot, so I'm closing this PR for now.

**Comment by willdurand** [comment]
we can discuss the feature in a issue (RFC)

**Pull request closed without merging**
