### PR TITLE
Fix User Warning: Multiple definitions for @OA\\Property()->title

### PR DESCRIPTION
**Pull request by mantis**
Fix for #1623

Phpdoc reader update property checks for title and if blank updates the property.
This should therefore run after the OA3 Annotations processing of title.

### CODE REVIEW

**Comment by GuilhemN** [comment]
Thanks!
Could you add a small test case to prevent future regression please? :)

**Comment by mantis** [comment]
I'll do this before bed (UK timezone here), but after shopping to buy food+beer ;)

**Comment by mantis** [comment]
@GuilhemN btw, the setup() constructor for tests has changed in phpunit - is needing :void for me

**Comment by mantis** [comment]
@GuilhemN Hopefully the updated test class will be appropriate for this?

**Comment by GuilhemN** [comment]
Yes, it's great :+1: 
Thank you @mantis :)

**Pull request merged**
