### PR TITLE
Solving error on this class

### PR DESCRIPTION
**Pull request by sinner**
I'm having this error at the moment I visit the NelmioApiDoc URL.

Notice: Undefined index: required

KernelException.php on line 57:
GetResponseForExceptionEvent {#1191 ▼
  -exception: ContextErrorException {#3274 ▼
    -context: array:7 [▶]
    #message: "Notice: Undefined index: required"
    #code: 0
    #file: "/var/www/api-onereach-basic/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Formatter/AbstractFormatter.php"
    #line: 75
    #severity: E_NOTICE
    trace: {▼
      /var/www/api-onereach-basic/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Formatter/AbstractFormatter.php:75 {▼
        › 'readonly'     => array_key_exists('readonly', $info) ? $info['readonly'] : null,
        › 'required'     => $info['required'],
        › 'default'      => array_key_exists('default', $info) ? $info['default'] : null,
      }
      /var/www/api-onereach-basic/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Formatter/AbstractFormatter.php:125 {▶}
      /var/www/api-onereach-basic/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Formatter/AbstractFormatter.php:161 {▶}
      /var/www/api-onereach-basic/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Formatter/AbstractFormatter.php:35 {▶}
      /var/www/api-onereach-basic/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Controller/ApiDocController.php:26 {▶}
      /var/www/api-onereach-basic/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151 {▶}
      /var/www/api-onereach-basic/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68 {▶}
      /var/www/api-onereach-basic/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:202 {▶}
      /var/www/api-onereach-basic/web/app_dev.php:13 {▼
        › $request = Request::createFromGlobals();
        › $response = $kernel->handle($request);
        › $response->send();
        arguments: {▶}
      }
    }
  }
  -allowCustomResponseCode: false
  -response: null
  -kernel: HttpKernel {#1696 ▶}
  -request: Request {#10 ▶}
  -requestType: 1
  -propagationStopped: false
}

### CODE REVIEW

**Comment by dbu** [comment]
i think version 2 is no longer maintained, hence all the build failures.

is this problem also present in version 3?

**Comment by sinner** [comment]
Sorry, but the version that we are installing is following your documentation published on the Symfony site.

The hotfix is a minimal change and we are using this version because the Symfony site is showing it.

It would be very helpful.

**Comment by dbu** [comment]
ping @GuilhemN

**Comment by GuilhemN** [comment]
It's supposed to always exist normally but I guess it doesn't cost to merge this.
Thank you @sinner!

**Pull request merged**
