### PR TITLE
Update routing.yml

### PR DESCRIPTION
**Pull request by maisoui**
Replace deprecated "pattern" and "_method" by "path" and "methods"

### CODE REVIEW

**Comment by Filoz** [comment]
:+1:

**Comment by weaverryan** [comment]
:+1:

**Comment by willdurand** [comment]
Thanks!

**Comment by teohhanhui** [comment]
@Filoz You're right. That's wrong.

See http://symfony.com/doc/current/book/routing.html#adding-http-method-requirements

**Pull request merged**
