### PR TITLE
feat: update swagger-ui

### PR DESCRIPTION
**Pull request by DjordyKoert**
Updates swagger-ui to support openapi 3.1

### CODE REVIEW

**Comment by DjordyKoert** [comment]
@GuilhemN I simply ran the `update-js.sh` and this is the result. Would be cool if this could be merged 😄

**Comment by GuilhemN** [comment]
Thank you @DjordyKoert!

**Comment by DjordyKoert** [comment]
No problem, happy to help 😄 @GuilhemN

**Comment by DjordyKoert** [comment]
@GuilhemN can you release a new version? 😬 I think you forgot

**Comment by stollr** [comment]
I am also interested in a new release 😉

**Pull request merged**
