### PR TITLE
Fix property_exists for SymfonyConstraintAnnotationReader

### PR DESCRIPTION
**Pull request by akalineskou**

### CODE REVIEW

**Comment by GuilhemN** [comment]
Oops... indeed this is broken, it seems I broke the tests at the same time so I didn't catch this.
Thanks for the fix!

**Comment by akalineskou** [comment]
Thanks for a quick merge and release <3

**Comment by tino299** [comment]
Hi, can you tag V4.0.1 with this fix ? thanks

**Comment by GuilhemN** [comment]
Sure! It's done :)

**Pull request merged**
