### PR TITLE
Do not test on symfony 4

### PR DESCRIPTION
**Pull request by BigZ**
I'm not sure it's very wise to test on dev dependencies... Especially when it breaks the build.
Let's wait a bit to bring it back in :)

### CODE REVIEW

**Comment by hboomsma** [comment]
Is it not better to add `allow_failure`? I guess it is a good thing to support Symfony 4 in the future?

**Comment by GuilhemN** [comment]
It's not complicated to fix, I just don't have the time right now to fix it :)
I'd rather fix the issue than ignore it as we'll very likely just forget it.

**Comment by BigZ** [comment]
hardcoded dev versions sounds unstable anyway. what is the benefit of unreliable test results ?
fixing it + allow failure can somehow be ok while waiting for the stable release, but we'll have to change something on the build at release date anyway

**Comment by GuilhemN** [comment]
Tests are fixed now :) Thanks!

**Pull request closed without merging**
