### PR TITLE
Add return type hints

### PR DESCRIPTION
**Pull request by BafS**
Add some return type hints

### CODE REVIEW

**Comment by GuilhemN** [comment]
I don't think we should update our public signatures, this would create additional BC breaks that may harden the upgrade to v4 while not bringing huge benefits imo.

**Comment by BafS** [comment]
Okay, let's close this PR

**Comment by GuilhemN** [comment]
Thanks for the submission still :)

**Comment by BafS** [comment]
You're welcome !
Off topic but instead of creating a new issue; what do you think about having Redoc (https://github.com/Redocly/redoc) as frontend ? Or both options (redoc is basically a single js file)

**Comment by GuilhemN** [comment]
Sure, that would be nice to have both options :+1: For reference, it seems ApiPlatform added its support a while ago now: https://github.com/api-platform/core/pull/2384.

**Pull request closed without merging**
