### PR TITLE
[bugfix] Remove PHP >= 5.4 features

### PR DESCRIPTION
**Pull request by phansys**
|Q            |A     |
|---          |---   |
|Branch       |master|
|Bug fix?     |yes   |
|New feature? |no    |
|BC breaks?   |no    |
|Deprecations?|no    |
|Tests pass?  |yes   |
|Fixed tickets|      |
|License      |MIT   |
|Doc PR       |n/a   |

Refs:
* [short array syntax](https://github.com/nelmio/NelmioApiDocBundle/blob/89f459dc0742a91da0ccacbbe7d6e176a0efd5ed/Tests/Extractor/ApiDocExtractorTest.php#L446)
* [`callable` type hint](https://github.com/nelmio/NelmioApiDocBundle/blob/89f459dc0742a91da0ccacbbe7d6e176a0efd5ed/Tests/Extractor/CollectionDirectiveTest.php#L34)

### CODE REVIEW

**Comment by GuilhemN** [comment]
Can't we instead remove the features specific to 5.4?
We'll already remove its support in 3.0 so i'd like 2.x to keep it in case we want to release an important bug fix.

**Comment by phansys** [comment]
@GuilhemN, done.

**Comment by GuilhemN** [comment]
Can you fix the tests please ? https://travis-ci.org/nelmio/NelmioApiDocBundle/jobs/203151763 
If that's too hard we can consider just bumping the php requirement to 5.4 as you proposed at first.

**Comment by phansys** [comment]
I've added a stub for PHP < 5.4 missing `json` classes and constants, but Is frustrating to see some other issues, like this:
```
Fatal error: Call to undefined method ReflectionClass::newInstanceWithoutConstructor() in /home/travis/build/nelmio/NelmioApiDocBundle/Parser/FormTypeParser.php on line 405
```

**Comment by GuilhemN** [comment]
Well it seems we can't have a perfect support of php 5.3, so let's not bother and just bump the php constraint.
Merged in https://github.com/nelmio/NelmioApiDocBundle/commit/eab2d5d8fcbd759c4ae109b6060b7d90d4269952, thanks!

**Comment by phansys** [comment]
Thank you @GuilhemN.

**Pull request closed without merging**
