### PR TITLE
Update ApiDocExtractor.php

### PR DESCRIPTION
**Pull request by tumbochka**
https://github.com/nelmio/NelmioApiDocBundle/issues/671

### CODE REVIEW

**Comment by sdieunidou** [comment]
:+1:

**Comment by sdieunidou** [comment]
ping @willdurand

**Comment by catchamonkey** [comment]
Any further progress on this?

**Comment by sdieunidou** [comment]
@willdurand why not merge ?

**Comment by willdurand** [comment]
all pull requests have been closed. more on this in the next release page (writing the explanations right nowà

**Comment by willdurand** [comment]
@sdieunidou please read this: https://github.com/nelmio/NelmioApiDocBundle/releases/tag/2.10.0.

**Comment by catchamonkey** [comment]
@sdieunidou so do you need to re-open a new PR with the same change?
That would be great as it's still required I think.

**Comment by willdurand** [comment]
But I don't think muting the function solves anything here...

**Comment by catchamonkey** [comment]
@willdurand yes true, interestingly, having updated to the latest release, the issue is no longer present for me.

**Comment by willdurand** [comment]
cool!

**Comment by sdieunidou** [comment]
@willdurand I have try ; the error was fixed on last release (nelmio/api-doc-bundle updated from 2.9.0 to 2.10.1). I think you can closed the issue.

Thank for your work !

**Comment by willdurand** [comment]
tip top, thanks!

**Pull request closed without merging**
