### PR TITLE
remove FOSRest on symfony 5 test runs

### PR DESCRIPTION
**Pull request by smoench**
FOSRest does not support symfony 5 yet

### CODE REVIEW

**Comment by smoench** [comment]
@GuilhemN you may have a look at this PR as it would allow us to test ApiDocBundle with Symfony 5 but exclude FOSRest tests.

I think FOSRest doesn't get support for Symfony 5 anytime soon https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2049

**Comment by Saracevas** [comment]
@smoench @GuilhemN Any news on Symfony 5 release? :/

**Comment by adrienlucas** [comment]
FIY FoS/Rest is getting closer to Symfony 5 : https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2084
Not sure what to do about this MR tho.

**Comment by smoench** [comment]
When FOSRest gets Symfony 5 support I would keep the extraction of FOSRest test to its own test class. The travis.yml and the `class_exists` check in `TestKernel` could be reverted.

**Comment by Saracevas** [comment]
@smoench FOSRest now supports Symfony 5, is there a way to move forward with this?

**Comment by GuilhemN** [comment]
That's great, thanks!

**Pull request merged**
