### PR TITLE
Add name in @Model

### PR DESCRIPTION
**Pull request by thhan**
It add name in Model to documentates results better ApiDoc. #1292

### CODE REVIEW

**Comment by GuilhemN** [comment]
> You have to specify for each and each serialization group. I think this not handling easy anyway.

Well this affects the model directly, not just its name so it's different imo.

Wouldn't you prefer just having something like?
```yml
nelmio_api_doc:
    models:
        names:
            Foo: App\Entity\Foo
            Foo_light: {type: App\Entity\Foo, groups: [light]}

**Comment by GuilhemN** [comment]
:+1: for using the annotations though i'd rather use `@SWG\Definition::$definition`:
```php
/**
 * @SWG\Definition(definition={"FooDetail": null, "FooDetail": ["foo_detail"]})
 */
```
What do you think ?

**Comment by goetas** [comment]
I stumbled in the same problem. I agre that the current implementation is not working well as it will require to define names for everything and will not work well when there are many available groups.

**Comment by goetas** [comment]
@thhan 
> I suggest to add the definition in the entity annotation.

since currently no other metadata format are supported except of annotations  that will not work for us as the entities come from a third party package that we do not have control over it. having it defined in the configuration will work much better for us as example

**Comment by GuilhemN** [comment]
Just merged https://github.com/nelmio/NelmioApiDocBundle/pull/1312. Thanks !

**Pull request closed without merging**
