### PR TITLE
Added CollectionModelDescriber for Collection support

### PR DESCRIPTION
**Pull request by nataliaAznar**
Fix issue https://github.com/nelmio/NelmioApiDocBundle/issues/1346

### CODE REVIEW

**Comment by nataliaAznar** [comment]
This fixes issue https://github.com/nelmio/NelmioApiDocBundle/issues/1346

**Comment by GuilhemN** [comment]
For what cases do you need this ?
Arrays already supported by both the kms and the symfony serializers.

**Comment by GuilhemN** [comment]
I'd rather change the test in https://github.com/nelmio/NelmioApiDocBundle/blob/master/ModelDescriber/ObjectModelDescriber.php#L89 to `isCollection`.

**Comment by GuilhemN** [comment]
Closing in favor of https://github.com/nelmio/NelmioApiDocBundle/issues/1369

**Pull request closed without merging**
