### PR TITLE
rename extracted parameters with JMS metadata naming strategy

### LINKED ISSUE #529: Required field in Class Input
Im having a problem when trying to make a field in an entity a required one. I have the following Class :

```
use JMS\Serializer\Annotation as Rest;
use Symfony\Component\Validator\Constraints as Assert;

class ActivateSIMRequest
{

    /**
     * Array of ICCIDs
     * @Rest\Type("array<string>")
     */
    private $iccids;

    /**
     * Customer Solution Name
     * @Rest\Type("string")
     * @Assert\NotBlank()
     */
    private $customerSolution;
}
```

And the following controller method :

```
/**
 * Activates SIM(s) onto a specified Customer Solution
 * 
 * @ApiDoc(
 *  resource=true,
 *  description="Activate SIMs",
 *  requirements={
 *      {
 *          "name"="_format",
 *          "dataType"="string",
 *          "requirement"="json|xml",
 *          "description"="Request format - either json or xml"
 *      }
 *  },
 *  input="WL\APIBundle\Types\ActivateSIMRequest",
 *  output="WL\APIBundle\Types\RequestReturn",
 * )
 * @Rest\Post("/api/{_format}/activateSIM")
 */
public function activateSIMAction(Request $request, $_format)
```

The API Doc is duplicating the CustomerSolution Field :

```
Parameter            Type                  Required?          Format Description
customerSolution     string                true               {not blank}  
iccids[]             array of strings      false              Array of ICCIDs 
customer_solution    string                false              Customer Solution Name 
```

As you can see the $customerSolution field is being added twice - how can I get a required field added just once ?

### PR DESCRIPTION
**Pull request by VSilantyev**
fixes #529

### CODE REVIEW

**Comment by VSilantyev** [comment]
Are you not interested in this fix? Or should I change something? Add tests?

**Comment by willdurand** [comment]
I am but please see this: https://github.com/nelmio/NelmioApiDocBundle/releases/tag/2.10.0

**Comment by Apostropher** [comment]
Will this ever be merged?

**Comment by djaney** [comment]
Up

**Pull request closed without merging**
