### PR TITLE
Add annotations support at methods level when using the JMS serializer

### PR DESCRIPTION
**Pull request by GuilhemN**
Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1412

### CODE REVIEW

**Comment by goetas** [comment]
Whoa! This is huge!

**Comment by GuilhemN** [comment]
Thanks! Next step could be to leverage readOnly/write fields since they are more likely to be useful when using virtual properties :smile: 

Besides, do you think I should check `\property_exists($item, 'getter')` (or `$item instanceof JMS\Serializer\Metadata\PropertyMetadata`) since it is not enforced by the `ClassMetadata` typing?

**Comment by goetas** [comment]
I think that doing instance of property metadata is good enough. Almost all jms code relies on that property being that class

**Comment by GuilhemN** [comment]
Ok, thanks, let's merge it as is then :)

**Pull request merged**
