### PR TITLE
Using JMS\Discriminator for multiple input/output types.

### PR DESCRIPTION
**Pull request by michalschroeder**
Issue: https://github.com/nelmio/NelmioApiDocBundle/issues/285

Add possibility to use JMS\Discriminator to describe multiple input/output object types on endpoints.
For example if there is one base class AbstractUser and multiple subclasses: User, Admin, Moderator... etc

```
/**
 * @ApiDoc(
 *  output="Acme\Bundle\Entity\AbstractUser"
 * )
 */
public function getUsersAction()
{
}
```

```
<?php

namespace Acme\Bundle\Entity;

use JMS\Serializer\Annotation as JMS;
use JMS\Serializer\Annotation\Discriminator;

/**
 * @Discriminator(field = "type", map = {
 *      "user": "Acme\Bundle\Entity\User",
 *      "admin": "Acme\Bundle\Entity\Admin",
 *  }
 * })
 */
abstract class AbstractUser
{
    /**
     * @JMS\Type("string");
     */
    public $userName;
}
```

```
<?php

namespace Acme\Bundle\Entity;

class User extends AbstractUser
{
}
```

```
<?php

namespace Acme\Bundle\Entity;

class Admin extends AbstractUser
{
    /**
     * @JMS\Type("string");
     */
    public $extraField;
}
```

### CODE REVIEW

**Comment by clubdesarrolladores** [comment]
this pull request was not merge? why? is a usefull feature.

**Comment by ruscon** [comment]
+1 :(
can you merge ?

**Comment by ruscon** [comment]
ping ?

**Comment by moroine** [comment]
Any update ?

**Pull request closed without merging**
