### PR TITLE
Use Serializer Groups with other parsers

### PR DESCRIPTION
**Pull request by develth**
Hey there, 

I stumpled upon [this Pull Request](https://github.com/nelmio/NelmioApiDocBundle/pull/639) and sadly saw no progress on this feature. 
So i integrated and extended it in the current 2.x Version. 

Thanks
Thomas

### CODE REVIEW

**Comment by develth** [comment]
Sorry- forgot to close. Thanks for the notification.

**Comment by develth** [comment]
Ahh - big mistake..
the #1058 text should be here and #1054 should be in #1058.... i will update the comments.

**Comment by BigZ** [comment]
still some mixed up commits here
i think you want to keep 2661449 & dd48dd7 only, and add .idea/vcs.xml to your global .gitignore

**Comment by develth** [comment]
Yip - sorry. Will fix it those days. Or should i start a new PR?

**Comment by GuilhemN** [comment]
Closing as 2.0 is no longer maintained, for new features please target 3.0.

**Pull request closed without merging**
