### PR TITLE
Updated symfony dependencies. See #1925

### PR DESCRIPTION
**Pull request by benelori**
This PR updates composer.json to allow Symfony 6.
See https://github.com/nelmio/NelmioApiDocBundle/issues/1925

### CODE REVIEW

**Comment by benelori** [comment]
Tested both paths from the config on a fresh Symfony 6 create with Symfony CLI.

**Comment by GuilhemN** [comment]
Actually there's already work in progress in https://github.com/nelmio/NelmioApiDocBundle/pull/1914 but we're waiting for api-platform's upgrade to go further :)

**Comment by benelori** [comment]
I searched only the issues and there's a typo in the Symfony 6 one there, I guess that's why I didn't find it :D
I'll search in the PRs next time as well.

**Comment by GuilhemN** [comment]
No problem, thank you for your submission still!
Feel free to follow #1914 if you'd like to help fixing possible issues once we're unlocked 😁

**Pull request closed without merging**
